ref:
  sequence:       vari-bbc-versioned-references/2021-08-10_11.12.27_v6/data/mm10_gencode_plus_viruses_and_cfmedips/sequence/mm10_gencode_plus_viruses_and_cfmedips.fa
  fai:            vari-bbc-versioned-references/2021-08-10_11.12.27_v6/data/mm10_gencode_plus_viruses_and_cfmedips/sequence/mm10_gencode_plus_viruses_and_cfmedips.fa.fai
  index:          vari-bbc-versioned-references/2021-08-10_11.12.27_v6/data/mm10_gencode_plus_viruses_and_cfmedips/indexes/bwa/mm10_gencode_plus_viruses_and_cfmedips


